repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [markdown]
        additional_dependencies:
          - prettier@3.0.3

  - repo: local
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
        entry: markdown-link-check
        language: node
        files: \.md$
        additional_dependencies: ['markdown-link-check@3.11.2']
